trigger:
- dev

stages:
- stage: Anchorescan
  displayName: Build and push to staging registry
  jobs:
  - job: Anchorescan
    displayName: Anchorescan
    steps:
    - script: |
        docker build -t localbuild/testimage:ci -f Dockerfile .

    - task: Anchore@0
      inputs:
        image: 'localbuild/testimage:ci'
        customPolicyPath: '.anchore/policy.json'
        dockerfile: Dockerfile
        failBuild: false 

    - script: |
        echo $(policyStatus)

        echo $(billOfMaterials)
        cat $(billOfMaterials)

        echo $(vulnerabilities)
        cat $(vulnerabilities)
