trigger:
- dev

stages:
- stage: Staging
  displayName: Build and push to staging registry
  jobs:
  - job: Staging
    displayName: Staging
    steps:
    - script: |
        docker build -t localbuild/testimage:ci -f Dockerfile .

    - task: Anchore@0
      inputs:
        image: 'localbuild/testimage:ci'
      
        dockerfile: Dockerfile
        failBuild: false 

    - script: |
        echo $(policyStatus)

        echo $(billOfMaterials)
        

        echo $(vulnerabilities)
        
