trigger:
- dev

stages:
- stage: Anchore-scan
  displayName: Build and push to staging registry
  jobs:
  - job: Anchore-scan
    displayName: Anchore-scan
    steps:
    - script: |
        docker build -t localbuild/testimage:ci -f Dockerfile .

    - task: Anchore@0
      inputs:
        image: 'localbuild/testimage:ci'
        customPolicyPath: '.anchore/policy.json'
        dockerfile: Dockerfile
        failBuild: false 

    - script: |
        echo $(policyStatus)

        echo $(billOfMaterials)
        

        echo $(vulnerabilities)
        
